### PR TITLE
Feature/06  more responsive

### PR DESCRIPTION
**Pull request by sak55**

### CODE REVIEW

**Comment by sak55** [comment]
MY Issues...
https://github.com/TheIronYard--Orlando/FEE--2015--SPRING/issues/88

**Comment by mfees** [comment]
:+1: 
looks good except for the missing media queries ;)

**Comment by jrutishauser** [comment]
:+1: and :beer: :beer: :beer: :beer: :beer: :beer: :beer: :beer: :beer: :beer: :beer: :beer: :beer: :beer: :beer: :beer: :beer: :beer: :beer: :beer: :beer: :beer: :beer: :beer: :beer: :beer: :beer: :beer: :beer: :beer: :beer: :beer: :beer: :beer: :beer: :beer: :beer: :beer: :beer: :beer: :beer: :beer: :beer: :beer: :beer: :beer: :beer: :beer: :beer: :beer: :beer: :beer: :beer: :beer: :beer: :beer: :beer: :beer: :beer: :beer: :beer: :beer: :beer: :beer: :beer: :beer: :beer: :beer: :beer: :beer: :beer: :beer: :beer: :beer: :beer: :beer: :beer: :beer: :beer: :beer: :beer: :beer: :beer: :beer: :beer: :beer: :beer: :beer: :beer: :beer: :beer: :beer: :beer: :beer: :beer: :beer: :beer: :beer: :beer: :beer: :beer: :beer: :beer: :beer: :beer: :beer: :beer: :beer: :beer: :beer: :beer: thats about 100 beers

**Comment by jrutishauser** [comment]
:+1:

**Pull request merged**
