### PR TITLE
Feature/04  surf+paddle

### PR DESCRIPTION
**Pull request by sak55**
This is my Pull Request from feature/04-surf+paddle

### CODE REVIEW

**Comment by jgarcia99** [comment]
:+1:  return the dumb lol

**Comment by jrutishauser** [comment]
:+1:  positioning all the divs

**Comment by sak55** [comment]
Link to my pull request :beers: say cheers
sak55/TIY-Assignments#10

**Comment by sak55** [comment]
my wiki - in progress
https://github.com/sak55/TIY-Assignments/wiki/Growth-and-Fixed-Mindset

**Pull request merged**
