### PR TITLE
Feature/18  hello jquery

### PR DESCRIPTION
**Pull request by sak55**

### CODE REVIEW

**Comment by sak55** [comment]
### Known Issues
* Incorrect font
* sends data to pergutory
* button on bottom is not exactly centered
*  button font is still italic

**Comment by sak55** [comment]
My WIP
https://github.com/TheIronYard--Orlando/FEE--2015--SPRING/issues/226

**Comment by jaredstevick** [comment]
:+1:

**Comment by carolinapowers** [comment]
:+1:

**Pull request merged**
