### PR TITLE
Feature/24  helluva ride

### PR DESCRIPTION
**Pull request by sak55**
[Timeline](http://sak55.github.io/TIY-Assignments/timeline/index.html)

### CODE REVIEW

**Comment by carolinapowers** [comment]
:+1:

**Comment by sak55** [comment]
[String Calculator](http://sak55.github.io/TIY-Assignments/katas/string-calculator.js)

**Comment by sak55** [comment]
[Check Writing](http://sak55.github.io/TIY-Assignments/katas/string-calculator.js)

**Comment by mfees** [comment]
:+1:

**Comment by TaylorFoster90** [comment]
:+1:

**Comment by jaredstevick** [comment]
:+1:

**Comment by sak55** [comment]
### known issues
## string calc
* works great only for inputs of 0-20 and every multiple of 10 through 100

**Comment by sak55** [comment]
## known issues
**String-Calculator**
* works great only for inputs of 0-20 and every multiple of 10 through 100

**Pull request merged**
